server {
    listen 7432;

    root /usr/share/nginx/html;
    index index.html;

    auth_basic "Chinese App";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache audio files aggressively
    location ~* \.(mp3)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
